gc()

#####THIS PIECE OF CODE USES RESULTS GENERATED BY fit_JLS.R

library(data.table)
library(lassosum) #transform p value to correlation
library(doParallel) # foreach
library(R.utils)
library(pROC) # for AUC
# library(pryr) # check memory useage
JLS_population_weight <- c(0.2, 0.5, 0.8) #gamma parameter in the paper
# JLS_population_weight_one <- JLS_population_weight[2]
JLS_result_prefix <- '/raid6/Tianyu/PRS/sharable/result_internal/JLS_result_weight_is'
genotype_plink2_file <- '/raid6/Ron/prs/data/bert_sample/YRI.TUNE/YRI.TUNE'
genotype_plink_file <- '/raid6/Tianyu/PRS/sharable/data_internal/YRI.TUNE'
AUC_result_file <- '/raid6/Tianyu/PRS/sharable/result_internal/JLS_result_AUC.txt'
for(JLS_population_weight_index in 1:length(JLS_population_weight)){
  JLS_population_weight_one <- JLS_population_weight[JLS_population_weight_index]
  
  ###THE JLS MODELS ARE STORED SEPARATELY FOR DIFFERENT POPULATION WEIGHTS
  JLS_regression_coefficient_file <- paste0(JLS_result_prefix, 
                                            sprintf("%.2f",JLS_population_weight_one), '_coefficient.txt')
  JLS_regression_coefficient <- fread(JLS_regression_coefficient_file)
  
  JLS_result_one_weight_file <- paste0(JLS_result_prefix, 
                                       sprintf("%.2f",JLS_population_weight_one), '.Rdata')
  
  JLS_result_one_weight <- get(load(JLS_result_one_weight_file))
  
  ####NOW WE HAVE ALL THE COEFFICIENTS (BETA) FOR ONE WEIGHT (GAMMA)
  ####EACH OF THE COEFFICIENT VECTOR CORRESPONDS TO ONE L1 PENALTY (LAMBDA)
  for(l1_penalty_index in 1:length(JLS_result_one_weight$lambda)){
    
    ####WE NEED TO STORE THE BETA IN CERTAIN FORMAT TO LEVERAGE THE FAST PLINK SOFTWARE FOR PGS EVALUATION
    effect_size_df <- data.frame(SNP = JLS_regression_coefficient$ID, 
                                 A1 = unlist(lapply(strsplit(JLS_regression_coefficient$ID, ":"),`[[`,4)),
                                 BETA = JLS_regression_coefficient[, ..l1_penalty_index])
    
    selected_coefficient_file <- paste0(JLS_result_prefix, 
                                        sprintf("%.2f",JLS_population_weight_one),
                                        '_l1_penalty_is_',
                                        sprintf("%.4f",JLS_result_one_weight$lambda[l1_penalty_index]), '_coefficient.txt')
    write.table(effect_size_df, selected_coefficient_file, sep = "\t", quote = FALSE, row.names = FALSE)
    
    ####PLACE TO STORE THE PGS RESULTS
    PGS_file <- paste0(JLS_result_prefix, 
                       sprintf("%.2f",JLS_population_weight_one),
                       '_l1_penalty_is_',
                       sprintf("%.4f",JLS_result_one_weight$lambda[l1_penalty_index]), '_PGS')
    
    ###NOW THE REAL WORK IS HAPPENING
    plink2.command = paste("plink2 --nonfounders","--allow-no-sex","--threads", 8,"--memory", 25000,
                           "--bfile", genotype_plink_file ,
                           "--score", selected_coefficient_file, "header-read",1,2,
                           "--score-col-nums",3,
                           "--out",PGS_file,
                           sep=" ")
    
    system(plink2.command)
  }
}

###NOW CALCULATE AUC RESULTS FOR THE TESTING SAMPLE FOR EACH HYPERPARAMETER
JLS_AUC <- data.frame()
for(JLS_population_weight_index in 1:length(JLS_population_weight)){
  JLS_population_weight_one <- JLS_population_weight[JLS_population_weight_index]
  
  JLS_result_one_weight_file <- paste0(JLS_result_prefix, 
                                       sprintf("%.2f",JLS_population_weight_one), '.Rdata')
  
  JLS_result_one_weight <- get(load(JLS_result_one_weight_file))
  ####EACH OF THE COEFFICIENT VECTOR CORRESPONDS TO ONE L1 PENALTY (LAMBDA)
  for(l1_penalty_index in 1:length(JLS_result_one_weight$lambda)){
    
    ####PLACE TO STORE THE PGS RESULTS
    PGS_file <- paste0(JLS_result_prefix, 
                       sprintf("%.2f",JLS_population_weight_one),
                       '_l1_penalty_is_',
                       sprintf("%.4f",JLS_result_one_weight$lambda[l1_penalty_index]), '_PGS.sscore')
    PGS <- data.frame(fread(PGS_file))
    current_AUC <- auc(PGS$PHENO1, PGS[,ncol(PGS)])
    JLS_AUC <- rbind(JLS_AUC,
                     data.frame(JLS_population_weight = JLS_population_weight_one,
                                JLS_l1_penalty = JLS_result_one_weight$lambda[l1_penalty_index],
                                AUC = current_AUC))
  }
}
write.table(JLS_AUC, file = AUC_result_file)



###I USE THE FOLLOWING LINES TO MERGE THE CHR21 CHR22 PLINK FILES TOGETHER
# small_population_reference_prefix_21 <- '/raid6/Tianyu/PRS/sharable/data/YRI-chr21'
# small_population_reference_prefix_22 <- '/raid6/Tianyu/PRS/sharable/data/YRI-chr22'
# plink_merge_command <- paste0("plink --bfile ", small_population_reference_prefix_21,
#                               " --bmerge ", small_population_reference_prefix_22, ".bed ",
#                               small_population_reference_prefix_22, ".bim ", 
#                               small_population_reference_prefix_22, ".fam ",
#                               "--out ", small_population_reference_prefix_merged)
# system(plink_merge_command)


# plink_convert_command <- paste0("plink2 --pfile ", genotype_plink2_file,
#                                 " --make-bed --out ", genotype_plink_file) 
# 
# system(plink_convert_command)
####THERE SHOULD BE A FURTHER FOR LOOP FOR JLS_population_weight_one, FOR SIMPLICITY I OMIT IT IN THE EXAMPLE CODE.
