gc()

#####THIS PIECE OF CODE USES RESULTS GENERATED BY fit_JLS.R

library(data.table)
library(lassosum) #transform p value to correlation
library(doParallel) # foreach
library(R.utils)
# library(pROC) # for AUC 
# library(pryr) # check memory useage
JLS_population_weight <- c(0, 0.5, 1) #gamma parameter in the paper
JLS_population_weight_one <- JLS_population_weight[2]

JLS_result_prefix <- '/raid6/Tianyu/PRS/sharable/result/JLS_result_weight_is'
small_population_reference_prefix_merged <- '/raid6/Tianyu/PRS/sharable/data/YRI-chr21n22'
###I USE THE FOLLOWING LINES TO MERGE THE CHR21 CHR22 PLINK FILES TOGETHER
# small_population_reference_prefix_21 <- '/raid6/Tianyu/PRS/sharable/data/YRI-chr21'
# small_population_reference_prefix_22 <- '/raid6/Tianyu/PRS/sharable/data/YRI-chr22'
# plink_merge_command <- paste0("plink --bfile ", small_population_reference_prefix_21,
#                               " --bmerge ", small_population_reference_prefix_22, ".bed ",
#                               small_population_reference_prefix_22, ".bim ", 
#                               small_population_reference_prefix_22, ".fam ",
#                               "--out ", small_population_reference_prefix_merged)
# system(plink_merge_command)

###THE JLS MODELS ARE STORED SEPARATELY FOR DIFFERENT POPULATION WEIGHTS
JLS_regression_coefficient_file <- paste0(JLS_result_prefix, 
                                          sprintf("%.2f",JLS_population_weight_one), '_coefficient.txt')
JLS_regression_coefficient <- fread(JLS_regression_coefficient_file)

JLS_result_one_weight_file <- paste0(JLS_result_prefix, 
                                     sprintf("%.2f",JLS_population_weight_one), '.Rdata')

JLS_result_one_weight <- get(load(JLS_result_one_weight_file))

for(l1_penalty_index in 1:length(JLS_result_one_weight$lambda)){
  # column_name_of_coefficient <- paste0('l1_para_is_',JLS_result_one_weight$lambda[l1_penalty_index])
  effect_size_df <- data.frame(SNP = JLS_regression_coefficient$ID, 
                               A1 = unlist(lapply(strsplit(JLS_regression_coefficient$ID, ":"),`[[`,4)),
                               BETA = JLS_regression_coefficient[, ..l1_penalty_index])
  
  selected_coefficient_file <- paste0(JLS_result_prefix, 
                                      sprintf("%.2f",JLS_population_weight_one),
                                      '_l1_penalty_is_',
                                      sprintf("%.4f",JLS_result_one_weight$lambda[l1_penalty_index]), '_coefficient.txt')
  write.table(effect_size_df, selected_coefficient_file, sep = "\t", quote = FALSE, row.names = FALSE)
  
  PGS_file <- paste0(JLS_result_prefix, 
                     sprintf("%.2f",JLS_population_weight_one),
                     '_l1_penalty_is_',
                     sprintf("%.4f",JLS_result_one_weight$lambda[l1_penalty_index]), '_PGS')
  
  plink2.command = paste("plink2 --nonfounders","--allow-no-sex","--threads", 8,"--memory", 25000,
                         "--bfile", small_population_reference_prefix_merged ,
                         "--score", selected_coefficient_file, "header-read",1,2,
                         "--score-col-nums",3,
                         "--out",PGS_file,
                         sep=" ")
  
  system(plink2.command)
}
